name: Tests

on:
  push:
    branches:
      - dev
      - master

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-20.04

    steps:
      - name : Say Hellow world
        shell: bash
        run: echo Github actions workshop

  unit-tests:
    name: Run my unit-test
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        shell: bash
        run: make tests_run

      - name: Get coverage
        shell: bash
        run: make coverage